name: C/C++ ARMv7 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install ARMv7 cross-compilation tools
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          sudo apt install build-essential
          
      - name: Install cppunit
        run: sudo apt install -y libcppunit-dev

      - name: Compile with GCC for ARMv7
        run: |
          gcc testmem.c -o ./build/testmem-armv7 -static

      - name: Upload compiled binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: testmem-armv7
          path: ./build/testmem-armv7
